Map<String, String> localizationsEnUs() {
  Map<String, String> obj = {
    // User Interface Strings
    // Titles
    'menu': 'Menu',
    'profile': 'Profile',
    'register': 'Register',
    'recoverPassword': 'Recover Password',
    'historic': 'Historic',
    'registerProduct': 'Register Product',
    // Buttons
    'update': 'Update',
    'connect': 'Connect',
    'back': 'Back',
    'recover': 'Recover',
    'confirm': 'Confirm',
    'cart': 'Cart',
    'portuguese': 'Portuguese',
    'english': 'English',
    'logout': 'Logout',
    'managementMenu': 'Manage Menu',
    'managementPerfil': 'Manage Personal Profile',
    'yes': 'Yes',
    'no': 'No',
    'youSure': 'You Sure?',
    'AreYouSure': 'Are you sure you want to delete this item?',
    'create': 'Create',
    'managementEmployees': 'Manage Employees',
    'managementSales': 'Manage Sales',
    // Forms
    'username': 'Username',
    'password': 'Password',
    'repeatPassword': 'Repeat Password',
    'name': 'Name',
    'email': 'E-mail',
    'phone': 'Phone',
    'address': 'Address',
    'newEmail': 'New E-mail',
    'newAddress': 'New Address',
    'newPhone': 'New Phone',
    'newPassword': 'New Password',
    'newRepeatPassword': 'New Repeat Password',
    'observations': 'Observations',
    'giveMoneyBack': 'Give money back',
    'order': 'Order ',
    'status': 'Status ',
    'date': 'Date',
    'hour': 'Hour',
    'price': 'Price',
    'avaliableInMenu': 'Available on the menu',
    'image': 'Image',
    'user': 'User',
    'employees': 'Employees',
    'administrator': 'Administrator',
    'selectAccessLevel': 'Select to set the access level:   ',
    'selectDeliveredLevel': 'Select to set the delivered level:   ',
    // Struct
    'description': 'Description',
    'finalPrice': 'Final price',
    'amount': 'Amount',
    'totalMoney': 'Total: R\$',
    'qtd': 'Qtd.: ',
    'quantity': 'Quantity',
    'totalPrice': 'Price: R\$',
    'und': 'Und.',
    // Utils
    'moneySymbol': 'R\$',
    'acess0': 'User',
    'acess1': 'Employee',
    'acess2': 'Administrator',
    // System Message Strings
    // Success
    "registerSucess": "Your registration has been completed successfully! You can now log in and start exploring our app.",
    'productRegisterSucess': 'Product created successfully.',
    "updateSucess": "Data updated successfully.",
    'deleteSucess': 'Data deleted successfully.',
    "addCartSucess": "Item added to cart successfully.",
    'sucessPurchase': 'Request made successfully.',
    // Error
    "errorInvalidData": "Invalid data.",
    "errorEmptyLogin": "The Username or Password field is empty.",
    "errorCreateAccount": "Failed to create account. Try again or contact support.",
    "errorCreateAccount1": "Failed to create account. Username is already in use.",
    'errorServerDown': 'Server down. Try again later.',
    "errorLoadingProducts": "An error occurred while loading the products",
    "errorLoadingUsers": "An error occurred while loading the employees",
    "errorUpdate": "Error updating user data.",
    "errorUpdate2": "All fields are empty or null.",
    "errorUpdate3": "Error updating user data: Item not found.",
    "errorConfirmPurchase": "Error confirming purchase:",
    "errorPurshaceEmpty": "No items to confirm purchase.",
    "errorConnectServer": "Error trying to connect to the server.",
    "errorInvalidAcess": "Error when trying to access, invalid account access level.",
    // Validate
    "validateUsername": "Username must have at least 4 characters",
    "validatePassword1": "Password must have at least 8 characters",
    "validatePassword2": "Passwords do not match",
    "validateName": "Name cannot be empty",
    "validateEmail": "Invalid email format",
    "validateAddress": "Address cannot be empty",
    "validatePhone": "Invalid phone number format",
    // Struct
    "underReview": "Under review",
    "inPreparation": "In preparation",
    "onTheWay": "On the way",
    "delivered": "Delivered",
    'canceled': 'Canceled',
  };
  return obj;
}
