Map<String, String> localizationsPtBr() {
  Map<String, String> obj = {
    // User Interface Strings
    //Titulos
    'menu': 'Cardápio',
    'profile': 'Perfil',
    'register': 'Registrar',
    'recoverPassword': 'Recuperar Senha',
    'historic': 'Histórico',
    'registerProduct': 'Registrar Produto',
    //Botões
    'update': 'Atualizar',
    'connect': 'Conectar',
    'back': 'Voltar',
    'recover': 'Recuperar',
    'confirm': 'Confirmar',
    'cart': 'Carrinho',
    'portuguese': 'Português',
    'english': 'Inglês',
    'logout': 'Deslogar',
    'managementMenu': 'Gerenciar Cardápio',
    'managementPerfil': 'Gerenciar Perfil Pessoal',
    'yes': 'Sim',
    'no': 'Não',
    'youSure': 'Tem certeza?',
    'AreYouSure': 'Você tem certeza que deseja excluir esse item?',
    'create': 'Criar',
    'managementEmployees': 'Gerenciar Funcionários',
    'managementSales': 'Gerenciar Pedidos',
    //Formulários
    'username': 'Nome de Usuário',
    'password': 'Senha',
    'repeatPassword': 'Repetir senha',
    'name': 'Nome',
    'email': 'E-mail',
    'phone': 'Telefone',
    'address': 'Endereço',
    'newEmail': 'Novo e-mail',
    'newAddress': 'Novo endereço',
    'newPhone': 'Novo telefone',
    'newPassword': 'Nova senha',
    'newRepeatPassword': 'Repetir nova senha',
    'observations': 'Observações',
    'giveMoneyBack': 'Dar troco',
    'order': 'Pedido',
    'status': 'Status',
    'date': 'Data',
    'hour': 'Hora',
    'price': 'Preço',
    'avaliableInMenu': 'Disponível no menu',
    'image': 'Imagem',
    'selectAccessLevel': 'Selecione para definir o nivel de acesso:   ',
    'selectDeliveredLevel': 'Selecione para definir o nivel de entrega:   ',
    // Estrutura
    'description': 'Descrição',
    'finalPrice': 'Preço final',
    'amount': 'Quantidade',
    'totalMoney': 'Total: R\$',
    'qtd': 'Qtd.: ',
    'quantity': 'Quantidade',
    'totalPrice': 'Preço: R\$',
    'und': 'Und.',
    // Utilitarios
    'moneySymbol': 'R\$',
    'acess0': 'Usuário',
    'acess1': 'Funcionario',
    'acess2': 'Administrador',
    // === Mensagens do Sistema:
    // Sucesso
    'registerSucess': 'Seu registro foi concluído com sucesso! Você pode agora fazer login e explorar nosso aplicativo.',
    'productRegisterSucess': 'Produto criado com sucesso.',
    'updateSucess': 'Dados atualizados com sucesso.',
    'deleteSucess': 'Dados deletados com sucesso.',
    'addCartSucess': 'Item adicionado ao carrinho com sucesso.',
    'sucessPurchase': 'Pedido realizado com sucesso.',
    // Erro
    'errorInvalidData': 'Dados inválidos.',
    'errorEmptyLogin': 'O campo Usuário ou Senha está vazio.',
    'errorCreateAccount': 'Falha ao criar conta. Tente novamente ou entre em contato com o suporte.',
    'errorCreateAccount1': 'Falha ao criar conta. Nome de Usuário já está em uso.',
    'errorServerDown': 'Servidor fora do ar. Tente novamente mais tarde.',
    'errorLoadingProducts': 'Ocorreu um erro ao carregar os produtos.',
    'errorLoadingUsers': 'Ocorreu um erro ao carregar os funcionarios.',
    'errorUpdate': 'Erro ao atualizar os dados do usuário.',
    'errorUpdate2': 'Todos os campos estão vazios ou nulos.',
    "errorUpdate3": "Erro ao atualizar os dados do usuário: Item não encontrado.",
    "errorConfirmPurchase": "Erro ao confirmar compra:",
    "errorPurshaceEmpty": "Sem items para confirmar a compra.",
    "errorConnectServer": "Erro ao tentar se conectar com o servidor.",
    "errorInvalidAcess": "Erro ao tentar acessar, nivel de acesso da conta inválido.",
    // Validação
    'validateUsername': 'O nome de usuário deve ter pelo menos 4 caracteres.',
    'validatePassword1': 'A senha deve ter pelo menos 8 caracteres.',
    'validatePassword2': 'As senhas não conferem.',
    'validateName': 'O nome não pode estar vazio.',
    'validateEmail': 'Formato de e-mail inválido.',
    'validateAddress': 'O endereço não pode estar vazio.',
    'validatePhone': 'Formato de telefone inválido.',
    // Estrutura:
    'all': 'Todos',
    'underReview': 'Em análise',
    'inPreparation': 'Em preparação',
    'onTheWay': 'A caminho',
    'delivered': 'Entregue',
    'canceled': 'Cancelado',
  };
  return obj;
}
